document:
  name: Allegato_A1_Introduzione_architettura_di_PagoPA_v1.0
  description: |
    Obiettivo strategico del sistema pagoPA è quello di facilitare e
    diffondere gli strumenti di pagamento elettronici, in particolare,
    quelli riferiti agli incassi della Pubblica Amministrazione, che da un
    lato associno, nel rispetto delle situazioni già in essere, benefici ai
    fini della gestione dei servizi di tesoreria, dall’altro consentano alla
    Pubblica Amministrazione di dotarsi di nuove modalità di rapporto con i
    cittadini e le imprese per tutte le problematiche di incasso,
    assicurando nel contempo un coordinamento a livello nazionale della
    concreta attuazione ed evoluzione nel tempo del sistema.  
  tags:
    - SANP
    - pagoPA
    - PA
    - AgID
